spring:
  application:
    name: MSConfigServer
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/User/Documents/ProyectosJava/Arka/config_server_files
          default-label: main
          clone-on-start: true
    bus:
      enabled: true
      refresh:
        enabled: true

  security:
    user:
      name: admin
      password: admin123
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh,refresh,health,info,metrics
    base-path: /actuator
  endpoint:
    health:
      show-details: always

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    eureka-server-connect-timeout-seconds: 10
  instance:
    hostname: localhost
    prefer-ip-address: true
